services:
  mariadb:
    image: 'mariadb:11.4.7'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '9006:3306' # Map port 9006 on the host to port 3306 on the container
