services:
  mariadb:
    # Pin version for image 'mariadb:11.4.7' with specific digest hash
    image: mariadb@sha256:1d18f91deb21136d1881705720071d1b474a9904ecca827058bf1c0fc64d3118
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MARIADB_DATABASE=${ENV_MARIADB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${ENV_MARIADB_PASSWORD}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 8s # Gives MariaDB a grace period before checks begin
      interval: 5s # Checks every 5 seconds
      timeout: 5s # Maximum amount of time Docker will wait for the healthcheck command
      retries: 10 # Allows up to (interval * retries) seconds for MariaDB to become ready
    networks:
      - backend
    ports:
      # Opening the port only for debug purposes in development
      # toDo: close port when used in production! (potential security risk)
      - '9006:3306'
    volumes:
      # Mount host dir to persist MariaDB data outside the container
      - /mariadb-data:/var/lib/mysql
      # Mount initialization scripts (like create-databases)
      - ./scripts/initdb:/docker-entrypoint-initdb.d

  backend-dev:
    build:
      context: .
    image: showcase-app-backend-dev:0.0.1
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://showcase-app-mariadb-1:3306/showcase_dev
    networks:
      - backend
    ports:
      - "9007:8080"

networks:
  backend:
  frontend: