# copy content to application.properties and adjust pw
spring.application.name=backend
spring.datasource.url=jdbc:mariadb://localhost:3306/showcase
spring.datasource.username=root
spring.datasource.password=<yourSuperSafePW>
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update