# HOWTO use this template?
# 1. Copy content to /src/main/resources/application-debug.properties
# 2. Adjust database name, password etc

# Debug properties

# Database

# Use local MariaDB for debugging
spring.datasource.url=jdbc:mariadb://localhost:7306/showcase_debug
spring.datasource.username=root
spring.datasource.password=<yourSuperSafePW>
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# General

spring.application.name=showcase-backend
server.port=8090
server.servlet.context-path=/showcase-api